const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"public, max-age=60","X-Content-Type-Options":"nosniff"}});
const musicTerms=["music","artist","artists","rapper","rap","hip hop","r&b","album","single","song","track","release","concert","tour","show","festival","ticket","producer","beat","playlist","lyrics","mixing","mastering","label","streaming","spotify","apple music","youtube","billboard","chart","genre","band","singer","vocal","freestyle","discography","new music","friday","independent","indie","dj","venue","gig","music video"];
const hasMusic=s=>musicTerms.some(t=>s.toLowerCase().includes(t));
const esc=s=>String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
const getJson=async(url,ms=6500)=>{const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal});return r.ok?await r.json():null}catch{return null}finally{clearTimeout(t)}};
export async function onRequestPost({request}){
 let body;try{body=await request.json()}catch{return json({error:"Send a music question."},400)}
 const q=String(body.message||"").trim().slice(0,240);if(!q)return json({error:"Type a music question to get started."},400);
 const lower=q.toLowerCase();
 if(!hasMusic(q)&&!/(drake|kendrick|beyonce|taylor swift|john michell|chief keef|travis scott|doja cat|ray charles|louis armstrong|future|sza|j cole|tyler the creator|lil wayne|playboi carti|bad bunny|metro boomin)/i.test(q))return json({reply:"I’m Wayfinder, and I stay in the music lane 🎧 Ask me about an artist, song, album, new release, music news, production, playlists, or concerts. Try one of the quick prompts below.",kind:"guide",actions:[{label:"Find an artist",query:"Find artist Drake"},{label:"New music",query:"Show me new music releases"},{label:"Concerts",query:"Find music concerts near me"}]});
 if(/concert|tour|ticket|festival|venue|gig|live show|near me|nearby/.test(lower)){const city=(q.match(/\b(?:in|near|around)\s+([a-z][a-z .\x27-]{1,45})/i)||[])[1];return json({reply:city?"Let’s look for live music around "+city.trim()+". These searches open current event listings; confirm dates, venue details, and ticket seller before buying.":"Let’s find live music. Tell me your city and state for a tighter search, or open a current event search now. No exact address needed.",kind:"concerts",cards:[{title:"Bandsintown events",description:"Artist tours and local live-music listings.",url:"https://www.bandsintown.com/"},{title:"Songkick concerts",description:"Concert listings and artist tour dates.",url:"https://www.songkick.com/"},{title:"Ticketmaster music",description:"Search official event and ticket listings.",url:"https://www.ticketmaster.com/discover/concerts"}],actions:[{label:"Search an artist",query:"Find artist " + q.replace(/concerts?|tours?|tickets?|festivals?|near me|nearby|in\s+.+/ig,"").trim()}]});}
 if(/news|headline|what.s happening|latest|update|story|stories/.test(lower)){const term=q.replace(/music news|latest music news|news about|music headlines|what.s happening in music|latest|headlines|news|updates|stories/ig,"").trim();const search=term||"hip hop music";const rss=await fetch("https://news.google.com/rss/search?q="+encodeURIComponent(search+" music")+"&hl=en-US&gl=US&ceid=US:en").then(async r=>r.ok?await r.text():"").catch(()=>"");const items=[...rss.matchAll(/<item>([\s\S]*?)<\/item>/g)].slice(0,5).map(m=>{const pick=k=>(m[1].match(new RegExp("<"+k+">([\\s\\S]*?)<\\/"+k+">"))||[])[1]||"";return{title:pick("title").replace(/&amp;/g,"&").replace(/<[^>]+>/g,""),url:pick("link").trim(),description:"Music news result. Open the original source for full reporting."}}).filter(x=>x.title&&x.url);return json({reply:items.length?"Here are current music-news search results. Open the original publisher for the full story.":"I couldn’t retrieve the live news feed just now. You can still search current music coverage directly.",kind:"news",cards:items.length?items:[{title:"Google News — music",description:"Search current music headlines from multiple publishers.",url:"https://news.google.com/search?q=music"}]});}
 if(/release|new music|friday|drop|dropping|album|single|song|track|discography|catalog|playlist|recommend|recommendation/.test(lower)&&!/artist/.test(lower)){const term=q.replace(/show me|find|search|new music|music releases|new releases|friday releases|release radar|recommend|recommendations|albums|singles|songs|tracks|playlist|playlists|please/ig,"").trim();const url="https://music.apple.com/us/search?term="+encodeURIComponent(term||"new music");return json({reply:"I’ve routed that to a free music-catalog search. Results and artwork come from the catalog provider; availability varies by country.",kind:"releases",cards:[{title:term?"Search “"+term+"” on Apple Music":"Explore music on Apple Music",description:"Albums, singles, tracks and catalog artwork.",url:url},{title:"YouTube music search",description:"Find official videos, audio and artist channels.",url:"https://www.youtube.com/results?search_query="+encodeURIComponent((term||"new music")+" official music")}]});}
 const artistQ=q.replace(/^(please\s+)?(find|search for|search|look up|tell me about|who is|artist)\s+/i,"").replace(/\s+(music|artist|artists|catalog|discography|songs|tracks)$/i,"").trim();
 const data=artistQ?await getJson(new URL("/api/artist?q="+encodeURIComponent(artistQ),new URL(request.url).origin).toString()):null;
 if(data&&data.ok&&data.artists&&data.artists.length){return json({reply:"Found music-catalog matches for "+artistQ+". Catalog counts reflect the tracks returned by the public search source, not a guaranteed lifetime discography. Distribution status is not verified.",kind:"artists",cards:data.artists.slice(0,5).map(a=>({title:a.artistName,description:[a.primaryGenreName,a.catalogTrackCount?(a.catalogCountIsLowerBound?"50+ tracks returned":a.catalogTrackCount+" tracks returned"):"Catalog count unavailable"].filter(Boolean).join(" · "),image:a.artworkUrl||null,url:a.artistViewUrl||("https://music.apple.com/us/search?term="+encodeURIComponent(a.artistName))})),news:(data.news||[]).slice(0,3).map(n=>({title:n.title,description:"Music-news search result",url:n.link})),actions:[{label:"Find concerts",query:"Find concerts for "+artistQ},{label:"Search releases",query:"Search releases by "+artistQ}]})}
 const search="https://music.apple.com/us/search?term="+encodeURIComponent(artistQ||q);return json({reply:"I can help you follow that music search. I couldn’t get a structured artist match on this try, so here are direct catalog searches rather than guessed facts.",kind:"search",cards:[{title:"Apple Music search",description:"Search artists, albums and songs.",url:search},{title:"YouTube search",description:"Look for official audio, videos and artist channels.",url:"https://www.youtube.com/results?search_query="+encodeURIComponent(artistQ||q)}]});
}