const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"public, max-age=60","X-Content-Type-Options":"nosniff"}});
const musicTerms=["music","artist","artists","rapper","rap","hip hop","r&b","album","single","song","track","release","concert","tour","show","festival","ticket","producer","beat","playlist","lyrics","mixing","mastering","label","streaming","spotify","apple music","youtube","billboard","chart","genre","band","singer","vocal","freestyle","discography","new music","friday","independent","indie","dj","venue","gig","music video"];
const hasMusic=s=>musicTerms.some(t=>s.toLowerCase().includes(t));
const esc=s=>String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
const getJson=async(url,ms=6500)=>{const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal});return r.ok?await r.json():null}catch{return null}finally{clearTimeout(t)}};
export async function onRequestPost({request}){
 let body;try{body=await request.json()}catch{return json({error:"Send a music question."},400)}
 const q=String(body.message||"").trim().slice(0,240);if(!q)return json({error:"Type a music question to get started."},400);
 const lower=q.toLowerCase();
 if(!hasMusic(q)&&!/(drake|kendrick|beyonce|taylor swift|john michell|chief keef|travis scott|doja cat|ray charles|louis armstrong|future|sza|j cole|tyler the creator|lil wayne|playboi carti|bad bunny|metro boomin)/i.test(q))return json({reply:"I’m Wayfinder, and I stay in the music lane 🎧 Ask me about an artist, song, album, new release, music news, production, playlists, or concerts. Try one of the quick prompts below.",kind:"guide",actions:[{label:"Find an artist",query:"Find artist Drake"},{label:"New music",query:"Show me new music releases"},{label:"Concerts",query:"Find music concerts near me"}]});
 if(/concert|tour|ticket|festival|venue|gig|live show|near me|nearby/.test(lower)){const city=(q.match(/\b(?:in|near|around)\s+([a-z][a-z .\x27-]{1,45})/i)||[])[1];return json({reply:city?"Let’s look for live music around "+city.trim()+". These searches open current event listings; confirm dates, venue details, and ticket seller before buying.":"Let’s find live music. Tell me your city and state for a tighter search, or open a current event search now. No exact address needed.",kind:"concerts",cards:[{title:"Bandsintown events",description:"Artist tours and local live-music listings.",url:"https://www.bandsintown.com/"},{title:"Songkick concerts",description:"Concert listings and artist tour dates.",url:"https://www.songkick.com/"},{title:"Ticketmaster music",description:"Search official event and ticket listings.",url:"https://www.ticketmaster.com/discover/concerts"}],actions:[{label:"Search an artist",query:"Find artist " + q.replace(/concerts?|tours?|tickets?|festivals?|near me|nearby|in\s+.+/ig,"").trim()}]});}
 if(/production|mixing|mastering|beat|beats|vocal|vocals|recording|sound design|songwriting/.test(lower)){const topic=q.replace(/^(how can i|how do i|help me|tips for|give me|teach me|improve|how to)\s*/i,"").trim()||"music production";return json({reply:"Let’s work on "+topic+". Start with one change at a time: keep the vocal clearly in front, check the low end on headphones and speakers, leave headroom before mastering, and compare your mix at matched loudness. These are starting points—not a substitute for listening to your actual track.",kind:"production",cards:[{title:"Production tutorials",description:"Free video search for "+topic+".",url:"https://www.youtube.com/results?search_query="+encodeURIComponent(topic+" music production tutorial")},{title:"Mixing tutorials",description:"Free walkthroughs on vocals, EQ, compression and mix translation.",url:"https://www.youtube.com/results?search_query="+encodeURIComponent(topic+" mixing tutorial")}]})}
 if(/independent|indie|underground|emerging|discover|artists like|similar to/.test(lower)){const term=q.replace(/find|show me|discover|recommend|independent|indie|underground|emerging|artists like|similar to|artists|artist|hip hop|hip-hop|r&b|music/ig,"").trim()||"independent hip hop";return json({reply:"Here are free discovery searches for "+(term||"independent music")+". Catalog matches vary by service, so open a result to verify the artist and release.",kind:"discovery",cards:[{title:"Apple Music discovery",description:"Search the public music catalog.",url:"https://music.apple.com/us/search?term="+encodeURIComponent(q)},{title:"YouTube discovery",description:"Find artist channels, official audio and independent releases.",url:"https://www.youtube.com/results?search_query="+encodeURIComponent(q+" independent music")},{title:"Audius",description:"Explore music from independent creators.",url:"https://audius.co/"}]})}
 if(/news|headline|what.s happening|latest|update|story|stories/.test(lower)){const term=q.replace(/music news|latest music news|news about|music headlines|what.s happening in music|latest|headlines|news|updates|stories/ig,"").trim();const search=term||"hip hop music";const rss=await fetch("https://news.google.com/rss/search?q="+encodeURIComponent(search+" music")+"&hl=en-US&gl=US&ceid=US:en").then(async r=>r.ok?await r.text():"").catch(()=>"");const items=[...rss.matchAll(/<item>([\s\S]*?)<\/item>/g)].slice(0,5).map(m=>{const pick=k=>(m[1].match(new RegExp("<"+k+">([\\s\\S]*?)<\\/"+k+">"))||[])[1]||"";return{title:pick("title").replace(/&amp;/g,"&").replace(/<[^>]+>/g,""),url:pick("link").trim(),description:"Music news result. Open the original source for full reporting."}}).filter(x=>x.title&&x.url);return json({reply:items.length?"Here are current music-news search results. Open the original publisher for the full story.":"I couldn’t retrieve the live news feed just now. You can still search current music coverage directly.",kind:"news",cards:items.length?items:[{title:"Google News — music",description:"Search current music headlines from multiple publishers.",url:"https://news.google.com/search?q=music"}]});}
 if(/release|new music|friday|drop|dropping|album|single|song|track|discography|catalog|playlist|recommend|recommendation/.test(lower)&&!/artist/.test(lower)){const term=q.replace(/show me|find|search|new music|music releases|new releases|friday releases|release radar|recommend|recommendations|albums|singles|songs|tracks|playlist|playlists|please/ig,"").trim();const url="https://music.apple.com/us/search?term="+encodeURIComponent(term||"new music");return json({reply:"I’ve routed that to a free music-catalog search. Results and artwork come from the catalog provider; availability varies by country.",kind:"releases",cards:[{title:term?"Search “"+term+"” on Apple Music":"Explore music on Apple Music",description:"Albums, singles, tracks and catalog artwork.",url:url},{title:"YouTube music search",description:"Find official videos, audio and artist channels.",url:"https://www.youtube.com/results?search_query="+encodeURIComponent((term||"new music")+" official music")}]});}
 const artistQ=q.replace(/^(please\s+)?(find|search for|search|look up|tell me about|who is|artist)\s+/i,"").replace(/\s+(music|artist|artists|catalog|discography|songs|tracks)$/i,"").trim();
 const data=artistQ?await getJson(new URL("/api/artist-intel?q="+encodeURIComponent(artistQ),new URL(request.url).origin).toString()):null;
 if(data&&data.ok&&data.artist){
  const artistName=data.artist;
  const cards=[{title:artistName,description:[data.ai?.genre||"Music artist",data.artistImage?"Verified artist portrait":"Artist portrait unavailable — no cover art substituted"].join(" · "),image:data.artistImage||null,url:data.links?.apple||("https://music.apple.com/us/search?term="+encodeURIComponent(artistName))}];
  (data.music||[]).slice(0,4).forEach(t=>cards.push({title:t.title,description:[t.album||"Release",t.releaseDate?String(t.releaseDate).slice(0,4):""].filter(Boolean).join(" · "),image:t.artwork||null,url:t.apple||data.links?.apple||("https://music.apple.com/us/search?term="+encodeURIComponent(artistName))}));
  return json({reply:"Matched "+artistName+" through the artist intelligence route. The profile image is only shown when an exact artist portrait is returned; square images on the release cards are that release’s own artwork. Open the catalog source to verify details.",kind:"artists",cards,actions:[{label:"Open Artist Hub",query:"Open Artist Hub for "+artistName},{label:"Find concerts",query:"Find concerts for "+artistName},{label:"Search releases",query:"Search releases by "+artistName}]});
 }
 const search="https://music.apple.com/us/search?term="+encodeURIComponent(artistQ||q);return json({reply:"I couldn’t confirm an exact artist profile, so I’m not assigning random cover art. These direct searches let you verify the artist and releases at the source.",kind:"search",cards:[{title:"Apple Music search",description:"Search artists, albums and songs.",url:search},{title:"YouTube search",description:"Look for official audio, videos and artist channels.",url:"https://www.youtube.com/results?search_query="+encodeURIComponent(artistQ||q)}]});
}